"""empty message

Revision ID: 45df180054ba
Revises: 4a2284a312c1
Create Date: 2022-02-22 16:23:31.650129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45df180054ba'
down_revision = '4a2284a312c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=15), nullable=False, comment='主机用户名'))
        batch_op.add_column(sa.Column('password', sa.String(length=102), nullable=False, comment='主机密码'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
