"""empty message

Revision ID: 4a2284a312c1
Revises: a826e61362c9
Create Date: 2022-02-20 13:32:38.831078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a2284a312c1'
down_revision = 'a826e61362c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'env',
               existing_type=mysql.VARCHAR(length=2),
               type_=sa.String(length=4),
               existing_comment='环境',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'env',
               existing_type=sa.String(length=4),
               type_=mysql.VARCHAR(length=2),
               existing_comment='环境',
               existing_nullable=False)
    # ### end Alembic commands ###
