"""empty message

Revision ID: 4fa98a33343a
Revises: 45df180054ba
Create Date: 2022-02-22 18:10:46.002618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fa98a33343a'
down_revision = '45df180054ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('env',
               existing_type=mysql.VARCHAR(length=4),
               type_=sa.String(length=5),
               existing_comment='环境',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('env',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=4),
               existing_comment='环境',
               existing_nullable=False)

    # ### end Alembic commands ###
