"""empty message

Revision ID: 794ebc640e8f
Revises: 43a3d6ff50cc
Create Date: 2022-02-17 04:10:00.755564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '794ebc640e8f'
down_revision = '43a3d6ff50cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=80),
               type_=sa.String(length=102),
               existing_comment='用户密码',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.String(length=102),
               type_=mysql.VARCHAR(length=80),
               existing_comment='用户密码',
               existing_nullable=False)
    # ### end Alembic commands ###
