"""empty message

Revision ID: a826e61362c9
Revises: 794ebc640e8f
Create Date: 2022-02-19 14:33:49.038645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a826e61362c9'
down_revision = '794ebc640e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('env', sa.String(length=2), nullable=False, comment='环境'))
    op.alter_column('asset', 'hostname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False,
               existing_comment='主机名')
    op.alter_column('asset', 'ip',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False,
               existing_comment='内网ip')
    op.alter_column('asset', 'auth_type',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_comment='认证类型 0: 密码认证  1: 密钥认证')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'auth_type',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_comment='认证类型 0: 密码认证  1: 密钥认证')
    op.alter_column('asset', 'ip',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True,
               existing_comment='内网ip')
    op.alter_column('asset', 'hostname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True,
               existing_comment='主机名')
    op.drop_column('asset', 'env')
    # ### end Alembic commands ###
