"""empty message

Revision ID: c1ffbcf1bc13
Revises: 595be912e4e0
Create Date: 2022-03-08 16:22:59.666273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1ffbcf1bc13'
down_revision = '595be912e4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=345),
               type_=sa.String(length=1035),
               existing_comment='主机密码',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=1035),
               type_=mysql.VARCHAR(length=345),
               existing_comment='主机密码',
               existing_nullable=False)

    # ### end Alembic commands ###
