"""empty message

Revision ID: eb20b05bc4dc
Revises: c1ffbcf1bc13
Create Date: 2022-03-08 16:36:31.715260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb20b05bc4dc'
down_revision = 'c1ffbcf1bc13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=1035),
               type_=sa.String(length=345),
               existing_comment='主机密码',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=345),
               type_=mysql.VARCHAR(length=1035),
               existing_comment='主机密码',
               existing_nullable=False)

    # ### end Alembic commands ###
