"""empty message

Revision ID: ec596126e7c9
Revises: 4fa98a33343a
Create Date: 2022-02-24 14:11:44.644378

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec596126e7c9'
down_revision = '4fa98a33343a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('protocol',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.Boolean(),
               nullable=False,
               comment='协议 0:ssh 1:rdp 2:telnet 3:vnc',
               existing_comment='连接协议')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.alter_column('protocol',
               existing_type=sa.Boolean(),
               type_=mysql.VARCHAR(length=6),
               nullable=True,
               comment='连接协议',
               existing_comment='协议 0:ssh 1:rdp 2:telnet 3:vnc')

    # ### end Alembic commands ###
